# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml

homeassistant:
  packages: !include_dir_named packages

proxmoxve:
  - host: 192.168.0.40
    username: homeassistant@pve
    password: mdphomeassistant
    verify_ssl: false
    realm: pve
    nodes:
      - node: tesla
        vms:
          - 1008
          - 10000

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: "/"
      - type: disk_free
        arg: "/"
      - type: memory_use_percent
      - type: processor_temperature
      - type: last_boot
  - platform: sql
    db_url: !secret mariadb_url
    queries:
      - name: DB size
        query: 'SELECT table_schema "database", round(sum(data_length + index_length)/1024/1024,1) "value" FROM information_schema.TABLES WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: "value"
        unit_of_measurement: MB

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.50

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

recorder:
  db_url: !secret mariadb_url
  include:
    domains:
      - switch
      - media_player
      - sensor
      - binary_sensor

light:
  - platform: switch
    name: Ipn Light
    entity_id: switch.ipn_on_off
  - platform: switch
    name: Papier Light
    entity_id: switch.lampe_papier_on_off
