# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_number: !include input_number.yaml

proxmoxve:
  - host: 192.168.0.40
    username: homeassistant@pve
    password: mdphomeassistant
    verify_ssl: false
    realm: pve
    nodes:
      - node: tesla
        vms:
          - 1008
          - 10000

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: "/"
      - type: disk_free
        arg: "/"
      - type: memory_use_percent
      - type: processor_temperature
      - type: last_boot
  - platform: sql
    db_url: !secret mariadb_url
    queries:
      - name: DB size
        query: 'SELECT table_schema "database", round(sum(data_length + index_length)/1024/1024,1) "value" FROM information_schema.TABLES WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: "value"
        unit_of_measurement: MB

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.50

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

recorder:
  db_url: !secret mariadb_url
  include:
    domains:
      - switch
      - media_player
      - sensor
      - binary_sensor

climate:
  - platform: generic_thermostat
    name: Pieces de vie
    unique_id: studygenericthermostat
    heater: group.radiateur_pieces_de_vie
    target_sensor: sensor.temperature_pieces_de_vie
    min_temp: 15
    max_temp: 25
    ac_mode: false
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    away_temp: 16
    precision: 0.1
  - platform: generic_thermostat
    name: Chambre 2
    unique_id: chambre2genericthermostat
    heater: switch.radiateur_big_bedroom
    target_sensor: sensor.temp5_temperature
    min_temp: 15
    max_temp: 25
    ac_mode: false
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    away_temp: 16
    precision: 0.1

template:
  - sensor:
      - name: "Temperature pieces de vie"
        unique_id: "pieces_de_vie_temp"
        unit_of_measurement: "°C"
        state: >
          {% set salon = states('sensor.temp1_temperature') | float %}
          {% set cuisine = states('sensor.temp4_temperature') | float %}

          {{ ((salon + cuisine) / 2) | round(1) }}

light:
  - platform: switch
    name: Ipn Light
    entity_id: switch.ipn_on_off
  - platform: switch
    name: Papier Light
    entity_id: switch.lampe_papier_on_off

zha:
  device_config:
    cc:86:ec:ff:fe:e9:b1:30-1: # format: {ieee}-{endpoint_id}
      type: "switch"
    84:fd:27:ff:fe:6a:5d:b9-1:
      type: "switch"
    00:12:4b:00:24:c1:5d:1d-1:
      type: "switch"

switch:
  - platform: template
    switches:
      radiateur_cuisine:
        unique_id: radiateur_cuisine
        value_template: "{{ is_state('switch.sonoff_radiateur_cuisine', 'off') }}"
        turn_on:
          service: switch.turn_off
          target:
            entity_id: switch.sonoff_radiateur_cuisine
        turn_off:
          service: switch.turn_on
          target:
            entity_id: switch.sonoff_radiateur_cuisine
      radiateur_salon:
        unique_id: radiateur_salon
        value_template: "{{ is_state('switch.sonoff_radiateur_salon', 'off') }}"
        turn_on:
          service: switch.turn_off
          target:
            entity_id: switch.sonoff_radiateur_salon
        turn_off:
          service: switch.turn_on
          target:
            entity_id: switch.sonoff_radiateur_salon
      radiateur_big_bedroom:
        unique_id: radiateur_big_bedroom
        value_template: "{{ is_state('switch.sonoff_radiateur_chambre2', 'off') }}"
        turn_on:
          service: switch.turn_off
          target:
            entity_id: switch.sonoff_radiateur_chambre2
        turn_off:
          service: switch.turn_on
          target:
            entity_id: switch.sonoff_radiateur_chambre2
